#! /bin/sh
# the next line restarts using wish8.0 \
exec wish8.0 "$0" "$@"
# interface generated by SpecTcl version 1.1 from /home/ioi/ws/ide1.0/SpecTcl/pref_general.ui
#   root     is the parent window for this user interface

proc pref_general_ui {root args} {

	# this treats "." as a special case

	if {$root == "."} {
	    set base ""
	} else {
	    set base $root
	}
    
	frame $base.frame#2 \
		-borderwidth 4

	frame $base.frame#3 \
		-borderwidth 2 \
		-relief groove

	frame $base.frame#4 \
		-borderwidth 2 \
		-relief groove

	frame $base.frame#5

	frame $base.frame#1

	checkbutton $base.checkbutton#3 \
		-text {Fast machine mode} \
		-variable p(fast)

	label $base.label#3 \
		-text {Mouse gravity}

	entry $base.entry#2 \
		-cursor {} \
		-textvariable p(gravity) \
		-width 4

	checkbutton $base.checkbutton#5 \
		-text {Insert on widget drop on gridline} \
		-variable p(insert_on_gridline)

	label $base.label#4 \
		-text {Mouse Button}

	entry $base.entry#3 \
		-cursor {} \
		-textvariable p(button) \
		-width 4

	checkbutton $base.checkbutton#6 \
		-text {Center canvas in frame} \
		-variable p(center)

	label $base.label#5 \
		-text {Scroll Delay}

	entry $base.entry#4 \
		-cursor {} \
		-textvariable p(scroll_delay) \
		-width 4

	checkbutton $base.checkbutton#8 \
		-text {Confirm saves during compile?} \
		-variable p(confirm-save-layout)

	label $base.label#6 \
		-text {Scroll Size}

	entry $base.entry#5 \
		-cursor {} \
		-textvariable p(incr) \
		-width 4

	checkbutton $base.checkbutton#7 \
		-text {Delete key deletes widgets?} \
		-variable p(confirm-delete-item)

	checkbutton $base.checkbutton#11 \
		-text {Display field help?} \
		-variable p(help)

	checkbutton $base.checkbutton#10 \
		-text {Autosave on quit?} \
		-variable p(confirm-autosave-on-quit)

	label $base.label#7 \
		-text Delay:

	scale $base.scale#1 \
		-length 75 \
		-orient h \
		-showvalue 0 \
		-to 1000.0 \
		-variable p(balloondelay)

	checkbutton $base.checkbutton#13 \
		-text {Confirm replace file on save?} \
		-variable p(confirm-replace-on-save)

	checkbutton $base.checkbutton#14 \
		-text {Apply Defaults to new widgets?} \
		-variable p(apply-defaults-widgets)

	checkbutton $base.checkbutton#12 \
		-text {Erase help?} \
		-variable p(balloonhelpforget)

	button $base.button#1 \
		-command FindWidgets \
		-text {Find Widgets}

	label $base.label#8 \
		-text Length:

	scale $base.scale#3 \
		-length 75 \
		-orient h \
		-showvalue 0 \
		-to 4000.0 \
		-variable p(balloonlength)

	label $base.label#2 \
		-text {Extra widget options}

	entry $base.entry#1 \
		-cursor {} \
		-textvariable p(other_items)


	# Geometry management

	grid $base.frame#2 -in $root	-row 12 -column 2  \
		-columnspan 5 \
		-sticky ew
	grid $base.frame#3 -in $root	-row 8 -column 4  \
		-columnspan 3 \
		-sticky nesw
	grid $base.frame#4 -in $root	-row 10 -column 4  \
		-columnspan 3 \
		-rowspan 2 \
		-sticky ew
	grid $base.frame#5 -in $root	-row 2 -column 2  \
		-rowspan 9 \
		-sticky nesw
	grid $base.frame#1 -in $root	-row 2 -column 4  \
		-columnspan 3 \
		-rowspan 5 \
		-sticky nesw
	grid $base.checkbutton#3 -in $base.frame#5	-row 1 -column 1  \
		-sticky w
	grid $base.label#3 -in $base.frame#1	-row 1 -column 1  \
		-sticky e
	grid $base.entry#2 -in $base.frame#1	-row 1 -column 2  \
		-sticky w
	grid $base.checkbutton#5 -in $base.frame#5	-row 2 -column 1  \
		-sticky w
	grid $base.label#4 -in $base.frame#1	-row 2 -column 1  \
		-sticky e
	grid $base.entry#3 -in $base.frame#1	-row 2 -column 2  \
		-sticky w
	grid $base.checkbutton#6 -in $base.frame#5	-row 3 -column 1  \
		-sticky w
	grid $base.label#5 -in $base.frame#1	-row 3 -column 1  \
		-sticky e
	grid $base.entry#4 -in $base.frame#1	-row 3 -column 2  \
		-sticky w
	grid $base.checkbutton#8 -in $base.frame#5	-row 4 -column 1  \
		-sticky w
	grid $base.label#6 -in $base.frame#1	-row 4 -column 1  \
		-sticky e
	grid $base.entry#5 -in $base.frame#1	-row 4 -column 2  \
		-sticky w
	grid $base.checkbutton#7 -in $base.frame#5	-row 5 -column 1  \
		-sticky w
	grid $base.checkbutton#11 -in $base.frame#3	-row 1 -column 1  \
		-columnspan 2 \
		-sticky w
	grid $base.checkbutton#10 -in $base.frame#5	-row 6 -column 1  \
		-sticky w
	grid $base.label#7 -in $base.frame#3	-row 2 -column 1  \
		-sticky e
	grid $base.scale#1 -in $base.frame#3	-row 2 -column 2  \
		-sticky ew
	grid $base.checkbutton#14 -in $base.frame#5	-row 7 -column 1  \
		-sticky w
	grid $base.checkbutton#12 -in $base.frame#4	-row 1 -column 1  \
		-columnspan 2 \
		-sticky w
	grid $base.button#1 -in $root	-row 11 -column 2  \
		-padx 2 \
		-pady 2
	grid $base.label#8 -in $base.frame#4	-row 2 -column 1  \
		-sticky e
	grid $base.scale#3 -in $base.frame#4	-row 2 -column 2  \
		-sticky ew
	grid $base.label#2 -in $base.frame#2	-row 1 -column 1  \
		-sticky e
	grid $base.entry#1 -in $base.frame#2	-row 1 -column 2  \
		-sticky ew

	# Resize behavior management

	grid rowconfigure $base.frame#2 1 -weight 0 -minsize -29
	grid columnconfigure $base.frame#2 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#2 2 -weight 1 -minsize 30

	grid rowconfigure $base.frame#3 1 -weight 0 -minsize -17
	grid rowconfigure $base.frame#3 2 -weight 0 -minsize -26
	grid columnconfigure $base.frame#3 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#3 2 -weight 1 -minsize 30

	grid rowconfigure $base.frame#4 1 -weight 0 -minsize -5
	grid rowconfigure $base.frame#4 2 -weight 0 -minsize -12
	grid columnconfigure $base.frame#4 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#4 2 -weight 0 -minsize 30

	grid rowconfigure $root 1 -weight 0 -minsize 5
	grid rowconfigure $root 2 -weight 0 -minsize 12
	grid rowconfigure $root 3 -weight 0 -minsize 9
	grid rowconfigure $root 4 -weight 0 -minsize 12
	grid rowconfigure $root 5 -weight 0 -minsize 11
	grid rowconfigure $root 6 -weight 0 -minsize 35
	grid rowconfigure $root 7 -weight 0 -minsize 1
	grid rowconfigure $root 8 -weight 0 -minsize -89
	grid rowconfigure $root 9 -weight 0 -minsize 2
	grid rowconfigure $root 10 -weight 0 -minsize -9
	grid rowconfigure $root 11 -weight 0 -minsize -36
	grid rowconfigure $root 12 -weight 0 -minsize -4
	grid rowconfigure $root 13 -weight 1 -minsize 8
	grid columnconfigure $root 1 -weight 0 -minsize 4
	grid columnconfigure $root 2 -weight 0 -minsize -134
	grid columnconfigure $root 3 -weight 0 -minsize 3
	grid columnconfigure $root 4 -weight 0 -minsize 30
	grid columnconfigure $root 5 -weight 1 -minsize 30
	grid columnconfigure $root 6 -weight 0 -minsize 30
	grid columnconfigure $root 7 -weight 0 -minsize 6

	grid rowconfigure $base.frame#5 1 -weight 0 -minsize -12
	grid rowconfigure $base.frame#5 2 -weight 0 -minsize -15
	grid rowconfigure $base.frame#5 3 -weight 0 -minsize -10
	grid rowconfigure $base.frame#5 4 -weight 0 -minsize -13
	grid rowconfigure $base.frame#5 5 -weight 0 -minsize -20
	grid rowconfigure $base.frame#5 6 -weight 0 -minsize -12
	grid rowconfigure $base.frame#5 7 -weight 0 -minsize -202
	grid columnconfigure $base.frame#5 1 -weight 0 -minsize 30

	grid rowconfigure $base.frame#1 1 -weight 0 -minsize -3
	grid rowconfigure $base.frame#1 2 -weight 0 -minsize -8
	grid rowconfigure $base.frame#1 3 -weight 0 -minsize -13
	grid rowconfigure $base.frame#1 4 -weight 0 -minsize -3
	grid columnconfigure $base.frame#1 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#1 2 -weight 0 -minsize 30
# additional interface code

# end additional interface code

}


# Allow interface to be run "stand-alone" for testing

catch {
    if [info exists embed_args] {
	# we are running in the plugin
	pref_general_ui .
    } else {
	# we are running in stand-alone mode
	if {$argv0 == [info script]} {
	    wm title . "Testing pref_general_ui"
	    pref_general_ui .
	}
    }
}
