#! /bin/sh
# the next line restarts using wish8.0 \
exec wish8.0 "$0" "$@"
# interface generated by SpecTcl version 1.1 from /home/ioi/ws/ide1.0/SpecTcl/pref_appearance.ui
#   root     is the parent window for this user interface

proc pref_appearance_ui {root args} {

	# this treats "." as a special case

	if {$root == "."} {
	    set base ""
	} else {
	    set base $root
	}
    
	frame $base.frame#40 \
		-borderwidth 2 \
		-relief groove

	frame $base.frame#44 \
		-borderwidth 2 \
		-relief groove

	frame $base.frame#29 \
		-borderwidth 2 \
		-relief groove

	frame $base.frame#32 \
		-borderwidth 2 \
		-relief groove

	frame $base.frame#1

	frame $base.frame#36 \
		-borderwidth 2 \
		-relief groove

	frame $base.frame#37

	frame $base.grid_bg_color \
		-borderwidth 2 \
		-relief sunken \
		-width 20

	frame $base.frame#41

	frame $base.selection_color \
		-borderwidth 2 \
		-relief sunken \
		-width 20

	frame $base.over_color \
		-borderwidth 2 \
		-relief sunken

	frame $base.can_bg \
		-borderwidth 2 \
		-relief sunken

	frame $base.frame#45

	frame $base.frame_bg \
		-borderwidth 2 \
		-relief sunken

	frame $base.frame#30

	frame $base.frame#33

	canvas $base.canvas#2 \
		-borderwidth 2 \
		-height 0 \
		-relief sunken \
		-width 0

	label $base.label#2 \
		-text {Grid Background Color:}
	catch {
		$base.label#2 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	label $base.label#6 \
		-text {Selection Color:}
	catch {
		$base.label#6 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	label $base.label#7 \
		-text {Active Color}
	catch {
		$base.label#7 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	label $base.label#8 \
		-text {Canvas Background}
	catch {
		$base.label#8 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	label $base.label#21 \
		-text {Frame background:}
	catch {
		$base.label#21 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	label $base.label#30 \
		-anchor e \
		-text {Editor Font Size} \
		-width 20
	catch {
		$base.label#30 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	radiobutton $base.radiobutton#1 \
		-anchor w \
		-text Small \
		-value 8 \
		-variable p(edit_font_size) \
		-width 7
	catch {
		$base.radiobutton#1 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	radiobutton $base.radiobutton#2 \
		-anchor w \
		-text Medium \
		-value 12 \
		-variable p(edit_font_size) \
		-width 7
	catch {
		$base.radiobutton#2 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	radiobutton $base.radiobutton#3 \
		-anchor w \
		-text Large \
		-value 18 \
		-variable p(edit_font_size) \
		-width 7
	catch {
		$base.radiobutton#3 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	label $base.label#31 \
		-anchor e \
		-text {Grid Thickness} \
		-width 20
	catch {
		$base.label#31 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	radiobutton $base.radiobutton#4 \
		-anchor w \
		-text Off \
		-value 0 \
		-variable p(grid_size) \
		-width 7
	catch {
		$base.radiobutton#4 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	radiobutton $base.radiobutton#5 \
		-anchor w \
		-text Thin \
		-value 3 \
		-variable p(grid_size) \
		-width 7
	catch {
		$base.radiobutton#5 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	radiobutton $base.radiobutton#6 \
		-anchor w \
		-text Thick \
		-value 6 \
		-variable p(grid_size) \
		-width 7
	catch {
		$base.radiobutton#6 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	label $base.label#25 \
		-anchor e \
		-text {Default Spacing} \
		-width 20
	catch {
		$base.label#25 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	radiobutton $base.radiobutton#10 \
		-anchor w \
		-text Small \
		-value 15 \
		-variable p(grid_spacing) \
		-width 7
	catch {
		$base.radiobutton#10 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	radiobutton $base.radiobutton#11 \
		-anchor w \
		-text Normal \
		-value 30 \
		-variable p(grid_spacing) \
		-width 7
	catch {
		$base.radiobutton#11 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	radiobutton $base.radiobutton#12 \
		-anchor w \
		-text Huge \
		-value 50 \
		-variable p(grid_spacing) \
		-width 7
	catch {
		$base.radiobutton#12 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	label $base.label#27 \
		-anchor e \
		-text {Initial Grid Size} \
		-width 20
	catch {
		$base.label#27 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	radiobutton $base.radiobutton#18 \
		-anchor w \
		-text Minimum \
		-value 4 \
		-variable p(maxrows) \
		-width 7
	catch {
		$base.radiobutton#18 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	radiobutton $base.radiobutton#17 \
		-anchor w \
		-text Normal \
		-value 6 \
		-variable p(maxrows) \
		-width 7
	catch {
		$base.radiobutton#17 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	radiobutton $base.radiobutton#16 \
		-anchor w \
		-text Many \
		-value 10 \
		-variable p(maxrows) \
		-width 7
	catch {
		$base.radiobutton#16 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	label $base.label#29 \
		-anchor e \
		-justify right \
		-text {Resize Handles} \
		-width 20
	catch {
		$base.label#29 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	radiobutton $base.radiobutton#22 \
		-text Small \
		-value 3 \
		-variable p(resize_handles)
	catch {
		$base.radiobutton#22 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	radiobutton $base.radiobutton#23 \
		-text Large \
		-value 6 \
		-variable p(resize_handles)
	catch {
		$base.radiobutton#23 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}


	# Geometry management

	grid $base.frame#40 -in $root	-row 7 -column 2  \
		-columnspan 5 \
		-sticky ew
	grid $base.frame#44 -in $root	-row 8 -column 2  \
		-columnspan 5 \
		-sticky ew
	grid $base.frame#29 -in $root	-row 4 -column 2  \
		-columnspan 5 \
		-sticky ew
	grid $base.frame#32 -in $root	-row 5 -column 2  \
		-columnspan 5 \
		-sticky ew
	grid $base.frame#1 -in $root	-row 2 -column 2  \
		-sticky ew
	grid $base.frame#36 -in $root	-row 6 -column 2  \
		-columnspan 5 \
		-sticky ew
	grid $base.frame#37 -in $base.frame#36	-row 1 -column 2  \
		-sticky ew
	grid $base.grid_bg_color -in $base.frame#1	-row 1 -column 2  \
		-sticky nesw
	grid $base.frame#41 -in $base.frame#40	-row 1 -column 2  \
		-sticky ew
	grid $base.selection_color -in $base.frame#1	-row 2 -column 2  \
		-sticky nesw
	grid $base.over_color -in $base.frame#1	-row 3 -column 2  \
		-sticky nesw
	grid $base.can_bg -in $base.frame#1	-row 4 -column 2  \
		-sticky nesw
	grid $base.frame#45 -in $base.frame#44	-row 1 -column 2  \
		-sticky ew
	grid $base.frame_bg -in $base.frame#1	-row 5 -column 2  \
		-sticky nesw
	grid $base.frame#30 -in $base.frame#29	-row 1 -column 2  \
		-sticky ew
	grid $base.frame#33 -in $base.frame#32	-row 1 -column 2  \
		-sticky ew
	grid $base.canvas#2 -in $root	-row 2 -column 4  \
		-columnspan 3 \
		-sticky nesw
	grid $base.label#2 -in $base.frame#1	-row 1 -column 1  \
		-sticky e
	grid $base.label#6 -in $base.frame#1	-row 2 -column 1  \
		-sticky e
	grid $base.label#7 -in $base.frame#1	-row 3 -column 1  \
		-sticky e
	grid $base.label#8 -in $base.frame#1	-row 4 -column 1  \
		-sticky e
	grid $base.label#21 -in $base.frame#1	-row 5 -column 1  \
		-sticky e
	grid $base.label#30 -in $base.frame#29	-row 1 -column 1 
	grid $base.radiobutton#1 -in $base.frame#30	-row 1 -column 1 
	grid $base.radiobutton#2 -in $base.frame#30	-row 1 -column 2 
	grid $base.radiobutton#3 -in $base.frame#30	-row 1 -column 3 
	grid $base.label#31 -in $base.frame#32	-row 1 -column 1 
	grid $base.radiobutton#4 -in $base.frame#33	-row 1 -column 1 
	grid $base.radiobutton#5 -in $base.frame#33	-row 1 -column 2 
	grid $base.radiobutton#6 -in $base.frame#33	-row 1 -column 3 
	grid $base.label#25 -in $base.frame#36	-row 1 -column 1 
	grid $base.radiobutton#10 -in $base.frame#37	-row 1 -column 1 
	grid $base.radiobutton#11 -in $base.frame#37	-row 1 -column 2 
	grid $base.radiobutton#12 -in $base.frame#37	-row 1 -column 3 
	grid $base.label#27 -in $base.frame#40	-row 1 -column 1 
	grid $base.radiobutton#18 -in $base.frame#41	-row 1 -column 1 
	grid $base.radiobutton#17 -in $base.frame#41	-row 1 -column 2 
	grid $base.radiobutton#16 -in $base.frame#41	-row 1 -column 3 
	grid $base.label#29 -in $base.frame#44	-row 1 -column 1  \
		-sticky e
	grid $base.radiobutton#22 -in $base.frame#45	-row 1 -column 1 
	grid $base.radiobutton#23 -in $base.frame#45	-row 1 -column 2 

	# Resize behavior management

	grid rowconfigure $base.frame#37 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#37 1 -weight 1 -minsize 30
	grid columnconfigure $base.frame#37 2 -weight 1 -minsize 30
	grid columnconfigure $base.frame#37 3 -weight 1 -minsize 30

	grid rowconfigure $base.frame#40 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#40 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#40 2 -weight 1 -minsize 30

	grid rowconfigure $base.frame#41 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#41 1 -weight 1 -minsize 30
	grid columnconfigure $base.frame#41 2 -weight 1 -minsize 30
	grid columnconfigure $base.frame#41 3 -weight 1 -minsize 30

	grid rowconfigure $root 1 -weight 0 -minsize 7
	grid rowconfigure $root 2 -weight 0 -minsize 142
	grid rowconfigure $root 3 -weight 0 -minsize 7
	grid rowconfigure $root 4 -weight 0 -minsize 22
	grid rowconfigure $root 5 -weight 0 -minsize 33
	grid rowconfigure $root 6 -weight 0 -minsize 30
	grid rowconfigure $root 7 -weight 0 -minsize 14
	grid rowconfigure $root 8 -weight 0 -minsize 11
	grid rowconfigure $root 9 -weight 0 -minsize 9
	grid columnconfigure $root 1 -weight 0 -minsize 6
	grid columnconfigure $root 2 -weight 0 -minsize 117
	grid columnconfigure $root 3 -weight 0 -minsize 7
	grid columnconfigure $root 4 -weight 1 -minsize 7
	grid columnconfigure $root 5 -weight 0 -minsize 30
	grid columnconfigure $root 6 -weight 0 -minsize 46
	grid columnconfigure $root 7 -weight 0 -minsize 6

	grid rowconfigure $base.frame#44 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#44 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#44 2 -weight 1 -minsize 30

	grid rowconfigure $base.frame#45 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#45 1 -weight 1 -minsize 30
	grid columnconfigure $base.frame#45 2 -weight 1 -minsize 30

	grid rowconfigure $base.frame#30 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#30 1 -weight 1 -minsize 30
	grid columnconfigure $base.frame#30 2 -weight 1 -minsize 30
	grid columnconfigure $base.frame#30 3 -weight 1 -minsize 30

	grid rowconfigure $base.frame#29 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#29 1 -weight 0 -minsize 99
	grid columnconfigure $base.frame#29 2 -weight 1 -minsize 30

	grid rowconfigure $base.frame#32 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#32 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#32 2 -weight 1 -minsize 30

	grid rowconfigure $base.frame#33 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#33 1 -weight 1 -minsize 30
	grid columnconfigure $base.frame#33 2 -weight 1 -minsize 30
	grid columnconfigure $base.frame#33 3 -weight 1 -minsize 30

	grid rowconfigure $base.frame#36 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#36 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#36 2 -weight 1 -minsize 30

	grid rowconfigure $base.frame#1 1 -weight 0 -minsize 13
	grid rowconfigure $base.frame#1 2 -weight 0 -minsize 14
	grid rowconfigure $base.frame#1 3 -weight 0 -minsize 2
	grid rowconfigure $base.frame#1 4 -weight 0 -minsize -3
	grid rowconfigure $base.frame#1 5 -weight 0 -minsize 6
	grid columnconfigure $base.frame#1 1 -weight 0 -minsize 111
	grid columnconfigure $base.frame#1 2 -weight 0 -minsize -40
# additional interface code

# end additional interface code

}


# Allow interface to be run "stand-alone" for testing

catch {
    if [info exists embed_args] {
	# we are running in the plugin
	pref_appearance_ui .
    } else {
	# we are running in stand-alone mode
	if {$argv0 == [info script]} {
	    wm title . "Testing pref_appearance_ui"
	    pref_appearance_ui .
	}
    }
}
