# interface generated by SpecTcl version 1.0 from /home/kcorey/hack/SpecTcl/SpecTcl/project.ui
#   root     is the parent window for this user interface

proc project_ui {root args} {

	# this treats "." as a special case

	if {$root == "."} {
	    set base ""
	} else {
	    set base $root
	}
    
	frame $base.frame#2 \
		-background #d9d9d9 \
		-highlightbackground #d9d9d9

	frame $base.frame#1 \
		-background #d9d9d9 \
		-highlightbackground #d9d9d9

	frame $base.frame#3 \
		-background #d9d9d9 \
		-highlightbackground #d9d9d9

	listbox $base.items \
		-background #d9d9d9 \
		-height 0 \
		-highlightbackground #d9d9d9 \
		-width 0 \
		-yscrollcommand "$base.scrollbar#1 set"
	catch {
		$base.items configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	scrollbar $base.scrollbar#1 \
		-background #d9d9d9 \
		-borderwidth 1 \
		-command "$base.listbox#1 yview" \
		-highlightbackground #d9d9d9 \
		-orient v

	button $base.button#1 \
		-background #d9d9d9 \
		-command project_add_file \
		-highlightbackground #d9d9d9 \
		-text {Add a file...}
	catch {
		$base.button#1 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	button $base.button#2 \
		-background #d9d9d9 \
		-command project_delete_file \
		-highlightbackground #d9d9d9 \
		-text {Delete file!}
	catch {
		$base.button#2 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	button $base.button#3 \
		-background #d9d9d9 \
		-command project_hide \
		-highlightbackground #d9d9d9 \
		-text Dismiss
	catch {
		$base.button#3 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}


	# Geometry management

	grid $base.frame#2 -in $root	-row 1 -column 2  \
		-columnspan 3 \
		-sticky ew
	grid $base.frame#1 -in $root	-row 2 -column 2  \
		-columnspan 3 \
		-rowspan 2 \
		-sticky nesw
	grid $base.frame#3 -in $root	-row 4 -column 2  \
		-columnspan 3 \
		-sticky ew
	grid $base.items -in $base.frame#1	-row 1 -column 1  \
		-sticky nesw
	grid $base.scrollbar#1 -in $base.frame#1	-row 1 -column 2  \
		-sticky ns
	grid $base.button#1 -in $base.frame#3	-row 1 -column 1 
	grid $base.button#2 -in $base.frame#3	-row 1 -column 2 
	grid $base.button#3 -in $base.frame#3	-row 1 -column 3 

	# Resize behavior management

	grid rowconfigure $base.frame#3 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#3 1 -weight 1 -minsize 30
	grid columnconfigure $base.frame#3 2 -weight 1 -minsize 75
	grid columnconfigure $base.frame#3 3 -weight 1 -minsize 30

	grid rowconfigure $root 1 -weight 0 -minsize 3
	grid rowconfigure $root 2 -weight 1 -minsize 155
	grid rowconfigure $root 3 -weight 0 -minsize 30
	grid rowconfigure $root 4 -weight 0 -minsize 30
	grid rowconfigure $root 5 -weight 0 -minsize 4
	grid columnconfigure $root 1 -weight 0 -minsize 6
	grid columnconfigure $root 2 -weight 0 -minsize 30
	grid columnconfigure $root 3 -weight 1 -minsize 30
	grid columnconfigure $root 4 -weight 0 -minsize 31
	grid columnconfigure $root 5 -weight 0 -minsize 4

	grid rowconfigure $base.frame#1 1 -weight 1 -minsize 30
	grid columnconfigure $base.frame#1 1 -weight 1 -minsize 114
	grid columnconfigure $base.frame#1 2 -weight 0 -minsize 2
# additional interface code
# end additional interface code

}
