START=.

OTHER=Makefile README

GIFS= 1.gif 10.gif 11.gif 12.gif 13.gif 14.gif 15.gif 16.gif \
	17.gif 18.gif 19.gif 2.gif 20.gif 21.gif 22.gif 23.gif \
	24.gif 3.gif 4.gif 5.gif 5a.gif 6.gif 7.gif 8.gif \
	9.gif anchor.gif aqball.gif borderwidth.gif fgcolor.gif \
	fill.gif font_size.gif gball.gif justify.gif l1.gif orient.gif \
	relief.gif style.gif aqdiamond.gif under.gif option.gif \
	b1.gif b2.gif b3.gif new.gif ball.gif finaltut.gif \
	finalrun.gif 12a.gif 10a.gif



HTML= glossary.html help.html interfacing.html options.html \
	quick.html ui.html bugs.html \
	tut0.html tut1.html tut2.html tut3.html tut4.html tut5.html \
	tut6.html tut7.html tut8.html tut9.html tut10.html \
	tut11.html tut12.html tut13.html tut14.html tut15.html \
	tut16.html tut17.html tut18.html tut19.html tut20.html \
	tut21.html tut22.html tut23.html tut24.html  \
	new.html changes.html javanotes.html misc.html tutorial.html \
	tutintro.html tut10a.html tut12a.html java.rc

list:
	@for i in $(OTHER) $(GIFS) $(HTML); do \
	echo  "$(START)/$$i"; \
	done

